application: columbo
version: 1
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?.*/.svn/.*
- ^(.*/)?.*/.git/.*
- ^(.*/)?.*/.hg/.*
- ^(.*/)?\..*$

builtins:
- remote_api: on
- datastore_admin: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine/appstats/ui.py

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /media
  static_dir: _generated_media/
  expiration: '365d'

- url: /admin.*
  script: djangoappengine/main/main.py
  secure: always

- url: /.*
  script: djangoappengine/main/main.py
  secure: always
